"""empty message

Revision ID: d8b50a576e28
Revises: c172e3993d71
Create Date: 2023-10-29 15:06:25.382136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b50a576e28'
down_revision = 'c172e3993d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['message'], ['rsvp.message'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
